/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tennis.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/tennis.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Tennis_CourtFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Tennis_Ball" position={[-206.89, 58.71, 15.18]} rotation={[0.7, 0, 0]} scale={[0.04, 0.03, 0.04]}>
                  <mesh name="Tennis_Ball_09_-_Default_0" geometry={nodes['Tennis_Ball_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                </group>
                <group name="Tennis_Racketzz" position={[-218.05, 66.72, 19.29]} rotation={[0, -1.57, 0]} scale={[0.03, 0.05, 0.02]}>
                  <mesh name="Tennis_Racketzz_02_-_Default_0" geometry={nodes['Tennis_Racketzz_02_-_Default_0'].geometry} material={materials['02_-_Default_0']} />
                  <mesh name="Tennis_Racketzz_03_-_Default_0" geometry={nodes['Tennis_Racketzz_03_-_Default_0'].geometry} material={materials['03_-_Default_0']} />
                  <mesh name="Tennis_Racketzz_07_-_Default_0" geometry={nodes['Tennis_Racketzz_07_-_Default_0'].geometry} material={materials['07_-_Default_0']} />
                </group>
                <group name="Tennis_Racketzz001" position={[228.03, 66.72, -44.56]} rotation={[0, -1.57, 0]} scale={[0.03, 0.05, 0.02]}>
                  <mesh name="Tennis_Racketzz001_02_-_Default_0" geometry={nodes['Tennis_Racketzz001_02_-_Default_0'].geometry} material={materials['02_-_Default_0']} />
                  <mesh name="Tennis_Racketzz001_03_-_Default_0" geometry={nodes['Tennis_Racketzz001_03_-_Default_0'].geometry} material={materials['03_-_Default_0']} />
                  <mesh name="Tennis_Racketzz001_07_-_Default_0" geometry={nodes['Tennis_Racketzz001_07_-_Default_0'].geometry} material={materials['07_-_Default_0']} />
                </group>
                <group name="Court" position={[0, -6.62, 6.62]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Court_01_-_Default_0" geometry={nodes['Court_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                  <mesh name="Court_08_-_Default_0" geometry={nodes['Court_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
                </group>
                <group name="Net" position={[0.18, -35, 6.86]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.08, 1, 0.85]}>
                  <mesh name="Net_02_-_Default_0" geometry={nodes['Net_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
                  <mesh name="Net_03_-_Default_0" geometry={nodes['Net_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
                  <mesh name="Net_07_-_Default_0" geometry={nodes['Net_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Root">
          <group name="Gp_Shuttle" position={[0.15, 0, 0]}>
            <group name="Obj_Cork">
              <mesh name="Obj_Cork_0" geometry={nodes.Obj_Cork_0.geometry} material={materials.White} position={[177.76, 42.58, -3.55]} rotation={[-1.19, -0.61, -2.04]} scale={176.2} />
            </group>
            <group name="Obj_Feather">
              <mesh name="Obj_Feather_0" geometry={nodes.Obj_Feather_0.geometry} material={materials.White} position={[177.76, 42.58, -3.55]} rotation={[-1.19, -0.61, -2.04]} scale={176.2} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tennis.glb')
