/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 tennis_court_animation.glb
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tennis-court-animation-fab5950b1b6f441da6a73c314f0cd04e
Title: Tennis Court (Animation)
*/

import React, { useEffect, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {



  // const group = useRef()
  const { nodes, materials, animations } = useGLTF('./tennis_court_animation.glb')
  const { ref, actions, names } = useAnimations(animations)
  const [index, setIndex] = useState(4)

  useEffect(() => {
    console.log(actions);
    // Reset and fade in animation after an index has been changed
    // actions[names]
    actions[names].reset().fadeIn(0.5).play()
    // In the clean-up phase, fade it out
    return () => actions[names].fadeOut(0.5)
  }, [index, actions, names])

  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Tennis_CourtFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group  onClick={() => setIndex((index + 1) % names.length)} name="Tennis_Ball" position={[-206.89, 100, 15.18]} rotation={[0.7, 0, 0]} scale={[0.04, 0.04, 0.04]}>
                  <mesh name="Tennis_Ball_09_-_Default_0" geometry={nodes['Tennis_Ball_09_-_Default_0'].geometry} material={materials['09_-_Default']} />
                </group>
                <group name="Tennis_Racketzz" position={[-218.05, 66.72, 19.29]} rotation={[0, -Math.PI / 2, 0]} scale={[0.03, 0.05, 0.02]}>
                  <mesh name="Tennis_Racketzz_03_-_Default_0" geometry={nodes['Tennis_Racketzz_03_-_Default_0'].geometry} material={materials['03_-_Default_0']} />
                  <mesh name="Tennis_Racketzz_02_-_Default_0" geometry={nodes['Tennis_Racketzz_02_-_Default_0'].geometry} material={materials['02_-_Default_0']} />
                  <mesh name="Tennis_Racketzz_07_-_Default_0" geometry={nodes['Tennis_Racketzz_07_-_Default_0'].geometry} material={materials['07_-_Default_0']} />
                </group>
                <group name="Tennis_Racketzz001" position={[228.03, 66.72, -44.56]} rotation={[0, -Math.PI / 2, 0]} scale={[0.03, 0.05, 0.02]}>
                  <mesh name="Tennis_Racketzz001_03_-_Default_0" geometry={nodes['Tennis_Racketzz001_03_-_Default_0'].geometry} material={materials['03_-_Default_0']} />
                  <mesh name="Tennis_Racketzz001_02_-_Default_0" geometry={nodes['Tennis_Racketzz001_02_-_Default_0'].geometry} material={materials['02_-_Default_0']} />
                  <mesh name="Tennis_Racketzz001_07_-_Default_0" geometry={nodes['Tennis_Racketzz001_07_-_Default_0'].geometry} material={materials['07_-_Default_0']} />
                </group>
                <group name="Court" position={[0, -6.62, 6.62]} rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="Court_08_-_Default_0" geometry={nodes['Court_08_-_Default_0'].geometry} material={materials['08_-_Default']} />
                  <mesh name="Court_01_-_Default_0" geometry={nodes['Court_01_-_Default_0'].geometry} material={materials['01_-_Default']} />
                </group>
                <group name="Net" position={[0.18, -35, 6.86]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.08, 1, 0.85]}>
                  <mesh name="Net_02_-_Default_0" geometry={nodes['Net_02_-_Default_0'].geometry} material={materials['02_-_Default']} />
                  <mesh name="Net_03_-_Default_0" geometry={nodes['Net_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
                  <mesh name="Net_07_-_Default_0" geometry={nodes['Net_07_-_Default_0'].geometry} material={materials['07_-_Default']} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./tennis_court_animation.glb')
